import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.scss'

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Todo app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={nunito.variable}
        style={{
          fontFamily: 'var(--font-nunito)',
        }}
      >
        {children}
      </body>
    </html>
  )
}
